SELECT COUNT(*)
FROM SHP_W01.SHIPPING_LOCATION;

SELECT *
FROM ALL_TAB_COLUMNS
WHERE OWNER LIKE 'SHP_W01' AND TABLE_NAME LIKE 'SHIPPING_LOCATION';

SELECT COUNT(*) FROM (
SELECT ZIP_CODE_AREA_ZIP_CODE_FROM, ZIP_CODE_AREA_ZIP_CODE_TO
FROM SHP_W01.SHIPPING_LOCATION
WHERE ZIP_CODE_AREA_ZIP_CODE_FROM IS NOT NULL AND ZIP_CODE_AREA_ZIP_CODE_TO IS NOT NULL
GROUP BY ZIP_CODE_AREA_ZIP_CODE_FROM, ZIP_CODE_AREA_ZIP_CODE_TO
);

SELECT COUNT(*) FROM (
SELECT COUNT(*), COUNTRY, STATE, city, zip_code_area_zip_code_from, zip_code_area_zip_code_to
FROM SHP_W01.SHIPPING_LOCATION
where zip_code_area_zip_code_from is not null and zip_code_area_zip_code_to is not null
GROUP BY COUNTRY, STATE, CITY, zip_code_area_zip_code_from, zip_code_area_zip_code_to
ORDER BY 1 DESC );

SELECT COUNT(*), COUNTRY, STATE, CITY
FROM SHP_W01.SHIPPING_LOCATION
GROUP BY COUNTRY, STATE, CITY
ORDER BY 1 DESC;

SELECT *
FROM ALL_TAB_COLUMNS
WHERE OWNER LIKE 'SHP_W01' AND TABLE_NAME LIKE 'RULES';

SELECT COUNT(*)
FROM SHP_W01.RULES;

SELECT COUNT(*)--ID, COUNTRY, STATE, CITY, zip_code_area_zip_code_from, zip_code_area_zip_code_to
FROM SHP_W01.SHIPPING_LOCATION
WHERE zip_code_area_zip_code_from IS NOT NULL AND zip_code_area_zip_code_to IS NOT NULL;

SELECT ID, COUNTRY, STATE, CITY
FROM SHP_W01.SHIPPING_LOCATION
WHERE COUNTRY LIKE 'BR' AND STATE LIKE 'BR-RJ' AND CITY LIKE 'BR-RJ-01'; 
SELECT *
FROM SHP_W01.SHIPPING_LOCATION
WHERE ID IN (17818715, 17818717);

SELECT *
FROM SHP_W01.RULES
WHERE SHIPPING_FROM_ID IN (SELECT ID
                            FROM SHP_W01.SHIPPING_LOCATION
                            WHERE COUNTRY LIKE 'BR' AND STATE LIKE 'BR-RJ' AND CITY LIKE 'BR-RJ-01')
ORDER BY SHIPPING_FROM_ID;
